import 'package:englishme/modules/exercise/models/exercise_model.dart';

class ExerciseRepository {
  // ignore: unused_field
  final dynamic _dio;

  ExerciseRepository(this._dio);

  Future<ExerciseSession> getExerciseSession({
    required ExerciseCategory category,
    int size = 10,
  }) async {
    await Future.delayed(const Duration(milliseconds: 800));
    return ExerciseSession(
      sessionId: 'fake-session-${category.name}',
      category: category,
      questions: category == ExerciseCategory.vocabulary
          ? _fakeVocabQuestions
          : _fakeGrammarQuestions,
    );
  }
}

const _fakeVocabQuestions = [
  ExerciseQuestion(
    id: 'v1',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.vocabulary,
    difficulty: ExerciseDifficulty.easy,
    question: '"Ambiguous" có nghĩa là gì?',
    options: ['Rõ ràng', 'Mơ hồ, không rõ ràng', 'Thông minh', 'Kiên nhẫn'],
    correctAnswer: 'Mơ hồ, không rõ ràng',
    explanation: 'Ambiguous = có nhiều hơn một nghĩa, khó xác định chính xác.',
  ),
  ExerciseQuestion(
    id: 'v2',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.vocabulary,
    difficulty: ExerciseDifficulty.medium,
    question: 'Chọn từ đồng nghĩa với "Eloquent".',
    options: ['Clumsy', 'Articulate', 'Silent', 'Confused'],
    correctAnswer: 'Articulate',
    explanation: 'Eloquent và Articulate đều có nghĩa là diễn đạt trôi chảy, hùng hồn.',
  ),
  ExerciseQuestion(
    id: 'v3',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.vocabulary,
    difficulty: ExerciseDifficulty.easy,
    question: '"Diligent" được dùng để mô tả người như thế nào?',
    options: ['Lười biếng', 'Cẩu thả', 'Chăm chỉ, siêng năng', 'Hung hăng'],
    correctAnswer: 'Chăm chỉ, siêng năng',
    explanation: 'Diligent = người có tính kiên trì, chăm chỉ trong công việc.',
  ),
  ExerciseQuestion(
    id: 'v4',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.vocabulary,
    difficulty: ExerciseDifficulty.hard,
    question: '"Ephemeral" gần nghĩa nhất với từ nào?',
    options: ['Permanent', 'Transient', 'Eternal', 'Solid'],
    correctAnswer: 'Transient',
    explanation: 'Ephemeral = tồn tại trong thời gian rất ngắn, tạm thời (transient).',
  ),
  ExerciseQuestion(
    id: 'v5',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.vocabulary,
    difficulty: ExerciseDifficulty.medium,
    question: 'Câu nào dùng "abundant" đúng nghĩa?',
    options: [
      'She had abundant of time to waste.',
      'The forest has abundant wildlife.',
      'He abundant his promise.',
      'They abundant the city.',
    ],
    correctAnswer: 'The forest has abundant wildlife.',
    explanation: 'Abundant = rất nhiều, dồi dào. Dùng như tính từ trước danh từ.',
  ),
  ExerciseQuestion(
    id: 'v6',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.vocabulary,
    difficulty: ExerciseDifficulty.easy,
    question: '"Concise" có nghĩa là gì?',
    options: ['Dài dòng', 'Ngắn gọn, súc tích', 'Lộn xộn', 'Phức tạp'],
    correctAnswer: 'Ngắn gọn, súc tích',
    explanation: 'Concise = trình bày ngắn gọn nhưng đầy đủ ý nghĩa.',
  ),
  ExerciseQuestion(
    id: 'v7',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.vocabulary,
    difficulty: ExerciseDifficulty.medium,
    question: 'Từ nào trái nghĩa với "Optimistic"?',
    options: ['Hopeful', 'Cheerful', 'Pessimistic', 'Confident'],
    correctAnswer: 'Pessimistic',
    explanation: 'Optimistic (lạc quan) ↔ Pessimistic (bi quan).',
  ),
  ExerciseQuestion(
    id: 'v8',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.vocabulary,
    difficulty: ExerciseDifficulty.hard,
    question: '"Ubiquitous" mô tả điều gì?',
    options: [
      'Hiếm gặp, quý giá',
      'Có mặt khắp nơi',
      'Bí ẩn, không rõ nguồn gốc',
      'Cũ kỹ, lỗi thời',
    ],
    correctAnswer: 'Có mặt khắp nơi',
    explanation: 'Ubiquitous = xuất hiện hoặc tồn tại ở khắp mọi nơi (vd: Smartphones are ubiquitous).',
  ),
  ExerciseQuestion(
    id: 'v9',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.vocabulary,
    difficulty: ExerciseDifficulty.easy,
    question: '"Generous" dùng để chỉ người như thế nào?',
    options: ['Keo kiệt', 'Rộng lượng, hào phóng', 'Ích kỷ', 'Lạnh lùng'],
    correctAnswer: 'Rộng lượng, hào phóng',
    explanation: 'Generous = sẵn sàng cho đi, không tiếc công sức hay tiền bạc.',
  ),
  ExerciseQuestion(
    id: 'v10',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.vocabulary,
    difficulty: ExerciseDifficulty.medium,
    question: 'Chọn nghĩa đúng của "Procrastinate".',
    options: [
      'Làm việc ngay lập tức',
      'Lên kế hoạch cẩn thận',
      'Trì hoãn, để việc đến sau',
      'Hoàn thành trước thời hạn',
    ],
    correctAnswer: 'Trì hoãn, để việc đến sau',
    explanation: 'Procrastinate = liên tục trì hoãn việc cần làm sang thời điểm khác.',
  ),
];

const _fakeGrammarQuestions = [
  ExerciseQuestion(
    id: 'g1',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.grammar,
    difficulty: ExerciseDifficulty.easy,
    question: 'Chọn dạng đúng:\n"She ___ to school every day."',
    options: ['go', 'goes', 'going', 'gone'],
    correctAnswer: 'goes',
    explanation: 'Chủ ngữ She (ngôi 3 số ít) + động từ thêm -s/es ở hiện tại đơn.',
  ),
  ExerciseQuestion(
    id: 'g2',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.grammar,
    difficulty: ExerciseDifficulty.medium,
    question: '"By the time she arrived, he ___ already left."\nChọn thì đúng.',
    options: ['has', 'had', 'have', 'was'],
    correctAnswer: 'had',
    explanation: 'Dùng Past Perfect (had + V3) cho hành động xảy ra trước một hành động khác trong quá khứ.',
  ),
  ExerciseQuestion(
    id: 'g3',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.grammar,
    difficulty: ExerciseDifficulty.easy,
    question: 'Câu nào dùng mạo từ đúng?',
    options: [
      'She is an university student.',
      'He bought a apple.',
      'I saw an elephant at the zoo.',
      'They live in a Europe.',
    ],
    correctAnswer: 'I saw an elephant at the zoo.',
    explanation: 'Dùng "an" trước âm nguyên âm (elephant bắt đầu bằng /e/).',
  ),
  ExerciseQuestion(
    id: 'g4',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.grammar,
    difficulty: ExerciseDifficulty.medium,
    question: '"If I ___ you, I would apologize."\nChọn dạng đúng.',
    options: ['am', 'was', 'were', 'be'],
    correctAnswer: 'were',
    explanation: 'Câu điều kiện loại 2 (giả định): If + S + were (dùng "were" cho mọi chủ ngữ).',
  ),
  ExerciseQuestion(
    id: 'g5',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.grammar,
    difficulty: ExerciseDifficulty.hard,
    question: 'Chọn câu bị động đúng cho:\n"The manager signed the contract yesterday."',
    options: [
      'The contract was signed by the manager yesterday.',
      'The contract is signed by the manager yesterday.',
      'The contract signed by the manager yesterday.',
      'The contract has been signed by the manager yesterday.',
    ],
    correctAnswer: 'The contract was signed by the manager yesterday.',
    explanation: 'Câu chủ động ở thì quá khứ đơn → bị động dùng was/were + V3.',
  ),
  ExerciseQuestion(
    id: 'g6',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.grammar,
    difficulty: ExerciseDifficulty.easy,
    question: '"I have lived here ___ 2010."\nChọn giới từ đúng.',
    options: ['for', 'since', 'during', 'from'],
    correctAnswer: 'since',
    explanation: '"Since" dùng với mốc thời gian cụ thể (năm, ngày). "For" dùng với khoảng thời gian.',
  ),
  ExerciseQuestion(
    id: 'g7',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.grammar,
    difficulty: ExerciseDifficulty.medium,
    question: 'Câu nào dùng đúng thì hiện tại hoàn thành?',
    options: [
      'I have seen that movie last night.',
      'She has just finished her homework.',
      'They have went to Paris in 2020.',
      'He has eat breakfast an hour ago.',
    ],
    correctAnswer: 'She has just finished her homework.',
    explanation: '"Just" thường đi với Present Perfect. Không dùng với mốc thời gian cụ thể (last night, in 2020, an hour ago).',
  ),
  ExerciseQuestion(
    id: 'g8',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.grammar,
    difficulty: ExerciseDifficulty.hard,
    question: '"___ he studies hard, he might pass the exam."\nChọn từ đúng.',
    options: ['Unless', 'Although', 'Provided that', 'Despite'],
    correctAnswer: 'Provided that',
    explanation: '"Provided that" = miễn là (điều kiện). "Unless" = trừ khi. "Although/Despite" = mặc dù.',
  ),
  ExerciseQuestion(
    id: 'g9',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.grammar,
    difficulty: ExerciseDifficulty.easy,
    question: 'Câu nào có lỗi sai?',
    options: [
      'He doesn\'t like coffee.',
      'Do she work here?',
      'They don\'t know the answer.',
      'Does he speak English?',
    ],
    correctAnswer: 'Do she work here?',
    explanation: 'Chủ ngữ "she" (ngôi 3 số ít) → phải dùng "Does she work here?"',
  ),
  ExerciseQuestion(
    id: 'g10',
    type: ExerciseType.multipleChoice,
    category: ExerciseCategory.grammar,
    difficulty: ExerciseDifficulty.medium,
    question: '"The book ___ on the table belongs to me."\nChọn mệnh đề quan hệ đúng.',
    options: ['who is', 'which is', 'whose is', 'whom is'],
    correctAnswer: 'which is',
    explanation: '"Which" dùng cho vật (the book). "Who/Whom" dùng cho người.',
  ),
];
