// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfRE62nyAXTo5SbIjIptNvfjKf90PBmF8',
    appId: '1:1094420115855:web:8f813203222f69e5755bfa',
    messagingSenderId: '1094420115855',
    projectId: 'english-me-cc094',
    authDomain: 'english-me-cc094.firebaseapp.com',
    storageBucket: 'english-me-cc094.firebasestorage.app',
    measurementId: 'G-H45D6M0C8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1frLO49YBLt_KIRa3paE2EmehDiqDYyQ',
    appId: '1:1094420115855:android:588cccd77f9d0d81755bfa',
    messagingSenderId: '1094420115855',
    projectId: 'english-me-cc094',
    storageBucket: 'english-me-cc094.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIRtYzx-GT47LvrPoHqE4m_ydtShzXBdY',
    appId: '1:1094420115855:ios:5fb675795f80d7b7755bfa',
    messagingSenderId: '1094420115855',
    projectId: 'english-me-cc094',
    storageBucket: 'english-me-cc094.firebasestorage.app',
    iosClientId: '1094420115855-77duducg4ui8fhkqbd8atst0gfgirogm.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIRtYzx-GT47LvrPoHqE4m_ydtShzXBdY',
    appId: '1:1094420115855:ios:5fb675795f80d7b7755bfa',
    messagingSenderId: '1094420115855',
    projectId: 'english-me-cc094',
    storageBucket: 'english-me-cc094.firebasestorage.app',
    iosClientId: '1094420115855-77duducg4ui8fhkqbd8atst0gfgirogm.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfRE62nyAXTo5SbIjIptNvfjKf90PBmF8',
    appId: '1:1094420115855:web:69e79a3933ff2d8e755bfa',
    messagingSenderId: '1094420115855',
    projectId: 'english-me-cc094',
    authDomain: 'english-me-cc094.firebaseapp.com',
    storageBucket: 'english-me-cc094.firebasestorage.app',
    measurementId: 'G-Q7TRKLV8K9',
  );
}
