import 'package:englishme/modules/test/models/test_model.dart';

class TestRepository {
  // ignore: unused_field
  final dynamic _dio;

  TestRepository(this._dio);

  Future<TestSession> getTestSession({
    required TestTopic topic,
    required TestLevel level,
  }) async {
    await Future.delayed(const Duration(milliseconds: 900));
    final questions = _fakeQuestions
        .where((q) => q.topic == topic && q.level == level)
        .toList();

    final allForTopic = _fakeQuestions.where((q) => q.topic == topic).toList();
    final pool = questions.isNotEmpty ? questions : allForTopic;

    return TestSession(
      sessionId: 'test-${topic.name}-${level.name}-${DateTime.now().millisecondsSinceEpoch}',
      topic: topic,
      level: level,
      questions: pool.take(10).toList(),
      durationSeconds: 15 * 60,
    );
  }

  Future<List<TestHistoryEntry>> getTestHistory() async {
    await Future.delayed(const Duration(milliseconds: 400));
    return _fakeHistory;
  }
}

final _fakeHistory = [
  TestHistoryEntry(
    sessionId: 'hist-1',
    topic: TestTopic.grammar,
    level: TestLevel.b1,
    correct: 8,
    total: 10,
    completedAt: DateTime.now().subtract(const Duration(days: 1)),
  ),
  TestHistoryEntry(
    sessionId: 'hist-2',
    topic: TestTopic.vocabulary,
    level: TestLevel.a2,
    correct: 6,
    total: 10,
    completedAt: DateTime.now().subtract(const Duration(days: 3)),
  ),
  TestHistoryEntry(
    sessionId: 'hist-3',
    topic: TestTopic.pronunciation,
    level: TestLevel.b2,
    correct: 7,
    total: 10,
    completedAt: DateTime.now().subtract(const Duration(days: 5)),
  ),
];

const _fakeQuestions = [
  // ── Grammar A1 ───────────────────────────────────────────────────────────────
  TestQuestion(
    id: 'ga1_1',
    topic: TestTopic.grammar,
    level: TestLevel.a1,
    question: 'Chọn dạng đúng:\n"They ___ students."',
    options: ['is', 'am', 'are', 'be'],
    correctAnswer: 'are',
    explanation: 'Chủ ngữ số nhiều "They" → dùng "are".',
  ),
  TestQuestion(
    id: 'ga1_2',
    topic: TestTopic.grammar,
    level: TestLevel.a1,
    question: '"I ___ a dog." Chọn từ đúng.',
    options: ['have', 'has', 'had', 'having'],
    correctAnswer: 'have',
    explanation: 'Ngôi 1 (I) dùng "have" ở hiện tại đơn.',
  ),
  TestQuestion(
    id: 'ga1_3',
    topic: TestTopic.grammar,
    level: TestLevel.a1,
    question: '"___ you from Vietnam?" Chọn từ đúng.',
    options: ['Is', 'Are', 'Am', 'Be'],
    correctAnswer: 'Are',
    explanation: 'Câu hỏi với "you" → "Are you...?"',
  ),
  TestQuestion(
    id: 'ga1_4',
    topic: TestTopic.grammar,
    level: TestLevel.a1,
    question: '"She ___ English every day." Chọn dạng đúng.',
    options: ['study', 'studies', 'studied', 'studying'],
    correctAnswer: 'studies',
    explanation: 'Ngôi 3 số ít + hiện tại đơn → thêm -ies (study → studies).',
  ),
  TestQuestion(
    id: 'ga1_5',
    topic: TestTopic.grammar,
    level: TestLevel.a1,
    question: 'Câu phủ định đúng của "He likes cats."',
    options: [
      'He not likes cats.',
      'He doesn\'t likes cats.',
      'He doesn\'t like cats.',
      'He don\'t like cats.',
    ],
    correctAnswer: 'He doesn\'t like cats.',
    explanation: 'Ngôi 3 số ít → doesn\'t + V nguyên thể (không chia).',
  ),
  TestQuestion(
    id: 'ga1_6',
    topic: TestTopic.grammar,
    level: TestLevel.a1,
    question: '"___ is your name?" Chọn từ đúng.',
    options: ['Who', 'What', 'Where', 'When'],
    correctAnswer: 'What',
    explanation: '"What is your name?" = Tên bạn là gì?',
  ),
  TestQuestion(
    id: 'ga1_7',
    topic: TestTopic.grammar,
    level: TestLevel.a1,
    question: 'Chọn câu đúng về mạo từ:',
    options: [
      'She is a engineer.',
      'He is an teacher.',
      'It is a cat.',
      'They are an students.',
    ],
    correctAnswer: 'It is a cat.',
    explanation: '"A" dùng trước danh từ bắt đầu bằng phụ âm. "Cat" bắt đầu bằng /k/.',
  ),
  TestQuestion(
    id: 'ga1_8',
    topic: TestTopic.grammar,
    level: TestLevel.a1,
    question: '"I ___ TV now." Chọn dạng tiếp diễn đúng.',
    options: ['watch', 'watches', 'am watching', 'is watching'],
    correctAnswer: 'am watching',
    explanation: 'Ngôi 1 + hành động đang xảy ra → am + V-ing.',
  ),
  TestQuestion(
    id: 'ga1_9',
    topic: TestTopic.grammar,
    level: TestLevel.a1,
    question: '"There ___ two books on the table."',
    options: ['is', 'are', 'am', 'be'],
    correctAnswer: 'are',
    explanation: '"There are" dùng với danh từ số nhiều (two books).',
  ),
  TestQuestion(
    id: 'ga1_10',
    topic: TestTopic.grammar,
    level: TestLevel.a1,
    question: 'Đại từ sở hữu của "I" là gì?',
    options: ['Me', 'My', 'Mine', 'Myself'],
    correctAnswer: 'My',
    explanation: '"My" là tính từ sở hữu (my book). "Mine" là đại từ sở hữu (this is mine).',
  ),

  // ── Grammar B1 ───────────────────────────────────────────────────────────────
  TestQuestion(
    id: 'gb1_1',
    topic: TestTopic.grammar,
    level: TestLevel.b1,
    question: '"By the time she arrived, he ___ already left."',
    options: ['has', 'had', 'have', 'was'],
    correctAnswer: 'had',
    explanation: 'Past Perfect cho hành động xảy ra trước một hành động khác trong quá khứ.',
  ),
  TestQuestion(
    id: 'gb1_2',
    topic: TestTopic.grammar,
    level: TestLevel.b1,
    question: '"If I ___ you, I would apologize."',
    options: ['am', 'was', 'were', 'be'],
    correctAnswer: 'were',
    explanation: 'Câu điều kiện loại 2 → If + S + were (dùng "were" cho mọi chủ ngữ).',
  ),
  TestQuestion(
    id: 'gb1_3',
    topic: TestTopic.grammar,
    level: TestLevel.b1,
    question: '"The contract ___ signed by the manager yesterday."',
    options: ['is', 'was', 'were', 'has been'],
    correctAnswer: 'was',
    explanation: 'Câu bị động ở quá khứ đơn → was + V3.',
  ),
  TestQuestion(
    id: 'gb1_4',
    topic: TestTopic.grammar,
    level: TestLevel.b1,
    question: '"I have lived here ___ 2010."',
    options: ['for', 'since', 'during', 'from'],
    correctAnswer: 'since',
    explanation: '"Since" dùng với mốc thời gian cụ thể. "For" dùng với khoảng thời gian.',
  ),
  TestQuestion(
    id: 'gb1_5',
    topic: TestTopic.grammar,
    level: TestLevel.b1,
    question: 'Câu nào dùng đúng thì hiện tại hoàn thành?',
    options: [
      'I have seen that movie last night.',
      'She has just finished her homework.',
      'They have went to Paris in 2020.',
      'He has eat breakfast an hour ago.',
    ],
    correctAnswer: 'She has just finished her homework.',
    explanation: '"Just" thường đi với Present Perfect. Không dùng mốc thời gian cụ thể.',
  ),
  TestQuestion(
    id: 'gb1_6',
    topic: TestTopic.grammar,
    level: TestLevel.b1,
    question: '"___ he studies hard, he might pass." Chọn từ đúng.',
    options: ['Unless', 'Although', 'Provided that', 'Despite'],
    correctAnswer: 'Provided that',
    explanation: '"Provided that" = miễn là (điều kiện). "Unless" = trừ khi.',
  ),
  TestQuestion(
    id: 'gb1_7',
    topic: TestTopic.grammar,
    level: TestLevel.b1,
    question: '"The book ___ on the table belongs to me." Chọn đúng.',
    options: ['who is', 'which is', 'whose is', 'whom is'],
    correctAnswer: 'which is',
    explanation: '"Which" dùng cho vật. "Who/Whom" dùng cho người.',
  ),
  TestQuestion(
    id: 'gb1_8',
    topic: TestTopic.grammar,
    level: TestLevel.b1,
    question: '"She ___ for 3 hours when the power went out." Chọn thì đúng.',
    options: ['was studying', 'had been studying', 'has been studying', 'studied'],
    correctAnswer: 'had been studying',
    explanation: 'Past Perfect Continuous: hành động kéo dài liên tục đến một thời điểm trong quá khứ.',
  ),
  TestQuestion(
    id: 'gb1_9',
    topic: TestTopic.grammar,
    level: TestLevel.b1,
    question: 'Chọn câu bị động đúng cho: "They are building a new bridge."',
    options: [
      'A new bridge is being built.',
      'A new bridge is built.',
      'A new bridge was being built.',
      'A new bridge has been built.',
    ],
    correctAnswer: 'A new bridge is being built.',
    explanation: 'Chủ động Present Continuous → Bị động: is/am/are + being + V3.',
  ),
  TestQuestion(
    id: 'gb1_10',
    topic: TestTopic.grammar,
    level: TestLevel.b1,
    question: '"He suggested ___ early." Chọn dạng đúng sau "suggest".',
    options: ['leave', 'to leave', 'leaving', 'left'],
    correctAnswer: 'leaving',
    explanation: '"Suggest" + V-ing (không dùng to-infinitive sau suggest).',
  ),

  // ── Grammar B2 ───────────────────────────────────────────────────────────────
  TestQuestion(
    id: 'gb2_1',
    topic: TestTopic.grammar,
    level: TestLevel.b2,
    question: '"Had I known earlier, I ___ differently." Chọn đúng.',
    options: ['would act', 'would have acted', 'will act', 'had acted'],
    correctAnswer: 'would have acted',
    explanation: 'Câu điều kiện loại 3 đảo ngữ: Had + S + V3 → S + would have + V3.',
  ),
  TestQuestion(
    id: 'gb2_2',
    topic: TestTopic.grammar,
    level: TestLevel.b2,
    question: 'Chọn câu đúng với "wish":',
    options: [
      'I wish I can speak French.',
      'I wish I could speak French.',
      'I wish I will speak French.',
      'I wish I spoke French tomorrow.',
    ],
    correctAnswer: 'I wish I could speak French.',
    explanation: '"Wish" + S + could/would/V2 → diễn tả điều ước ở hiện tại (không thể thực hiện).',
  ),
  TestQuestion(
    id: 'gb2_3',
    topic: TestTopic.grammar,
    level: TestLevel.b2,
    question: '"The more you practice, ___ you become." Chọn đúng.',
    options: ['the better', 'more better', 'the most better', 'better'],
    correctAnswer: 'the better',
    explanation: 'Cấu trúc so sánh tăng tiến: The + comparativeⅠ, the + comparativeⅡ.',
  ),
  TestQuestion(
    id: 'gb2_4',
    topic: TestTopic.grammar,
    level: TestLevel.b2,
    question: '"___ the bad weather, we decided to go out." Chọn đúng.',
    options: ['Despite', 'Although', 'However', 'Even though'],
    correctAnswer: 'Despite',
    explanation: '"Despite/In spite of" + cụm danh từ/V-ing. "Although/Even though" + mệnh đề.',
  ),
  TestQuestion(
    id: 'gb2_5',
    topic: TestTopic.grammar,
    level: TestLevel.b2,
    question: 'Chuyển sang giọng tường thuật:\n"I will help you," she said.',
    options: [
      'She said she will help me.',
      'She said she would help me.',
      'She told she would help me.',
      'She said she will help you.',
    ],
    correctAnswer: 'She said she would help me.',
    explanation: 'Reported Speech: will → would. "said" không đổi tân ngữ, đại từ "you" → "me".',
  ),
  TestQuestion(
    id: 'gb2_6',
    topic: TestTopic.grammar,
    level: TestLevel.b2,
    question: '"Not only ___ late, but he also forgot his ID." Chọn đúng.',
    options: [
      'he arrived',
      'did he arrive',
      'he did arrive',
      'arrived he',
    ],
    correctAnswer: 'did he arrive',
    explanation: '"Not only" đứng đầu câu → đảo ngữ (Not only + auxiliary + S + V).',
  ),
  TestQuestion(
    id: 'gb2_7',
    topic: TestTopic.grammar,
    level: TestLevel.b2,
    question: '"I need to have my car ___." Chọn đúng.',
    options: ['repair', 'repaired', 'repairing', 'to repair'],
    correctAnswer: 'repaired',
    explanation: 'Causative: have/get + O + V3 (past participle) → nhờ người khác làm.',
  ),
  TestQuestion(
    id: 'gb2_8',
    topic: TestTopic.grammar,
    level: TestLevel.b2,
    question: '"___ on time, he might have missed the train." Chọn đúng.',
    options: [
      'Unless he had arrived',
      'Had he not arrived',
      'If he arrives',
      'Would he arrive',
    ],
    correctAnswer: 'Had he not arrived',
    explanation: 'Câu điều kiện loại 3 đảo ngữ phủ định: Had + S + not + V3.',
  ),
  TestQuestion(
    id: 'gb2_9',
    topic: TestTopic.grammar,
    level: TestLevel.b2,
    question: 'Chọn câu dùng "used to" đúng:',
    options: [
      'I used to living in Hanoi.',
      'She is used to wake up early.',
      'He used to smoke but quit years ago.',
      'They use to play tennis on Sundays.',
    ],
    correctAnswer: 'He used to smoke but quit years ago.',
    explanation: '"Used to + V" = thói quen trong quá khứ, nay không còn nữa.',
  ),
  TestQuestion(
    id: 'gb2_10',
    topic: TestTopic.grammar,
    level: TestLevel.b2,
    question: '"By 2030, scientists ___ a cure for the disease." Chọn đúng.',
    options: [
      'will discover',
      'will have discovered',
      'are discovering',
      'have discovered',
    ],
    correctAnswer: 'will have discovered',
    explanation: 'Future Perfect: will have + V3 → hành động hoàn thành trước một thời điểm trong tương lai.',
  ),

  // ── Vocabulary A2 ─────────────────────────────────────────────────────────────
  TestQuestion(
    id: 'va2_1',
    topic: TestTopic.vocabulary,
    level: TestLevel.a2,
    question: '"Happy" có nghĩa là gì?',
    options: ['Buồn', 'Vui vẻ, hạnh phúc', 'Tức giận', 'Sợ hãi'],
    correctAnswer: 'Vui vẻ, hạnh phúc',
    explanation: 'Happy = cảm giác vui vẻ, hài lòng.',
  ),
  TestQuestion(
    id: 'va2_2',
    topic: TestTopic.vocabulary,
    level: TestLevel.a2,
    question: 'Từ nào là trái nghĩa của "big"?',
    options: ['Large', 'Huge', 'Small', 'Tall'],
    correctAnswer: 'Small',
    explanation: 'Big (to lớn) ↔ Small (nhỏ bé).',
  ),
  TestQuestion(
    id: 'va2_3',
    topic: TestTopic.vocabulary,
    level: TestLevel.a2,
    question: '"Friend" dịch sang tiếng Việt là gì?',
    options: ['Kẻ thù', 'Bạn bè', 'Gia đình', 'Đồng nghiệp'],
    correctAnswer: 'Bạn bè',
    explanation: 'Friend = người bạn, bạn bè.',
  ),
  TestQuestion(
    id: 'va2_4',
    topic: TestTopic.vocabulary,
    level: TestLevel.a2,
    question: '"Beautiful" được dùng để mô tả điều gì?',
    options: ['Thứ xấu xí', 'Thứ đẹp đẽ', 'Thứ nguy hiểm', 'Thứ đắt tiền'],
    correctAnswer: 'Thứ đẹp đẽ',
    explanation: 'Beautiful = đẹp đẽ, xinh đẹp.',
  ),
  TestQuestion(
    id: 'va2_5',
    topic: TestTopic.vocabulary,
    level: TestLevel.a2,
    question: 'Chọn từ điền vào: "I ___ to school by bus."',
    options: ['go', 'run', 'swim', 'fly'],
    correctAnswer: 'go',
    explanation: '"Go to school" = đi học. Thường dùng "go" để nói về việc di chuyển đến nơi nào đó.',
  ),
  TestQuestion(
    id: 'va2_6',
    topic: TestTopic.vocabulary,
    level: TestLevel.a2,
    question: '"Hungry" nghĩa là gì?',
    options: ['Khát nước', 'Đói bụng', 'Mệt mỏi', 'Buồn ngủ'],
    correctAnswer: 'Đói bụng',
    explanation: 'Hungry = cảm giác đói, muốn ăn.',
  ),
  TestQuestion(
    id: 'va2_7',
    topic: TestTopic.vocabulary,
    level: TestLevel.a2,
    question: 'Từ nào đồng nghĩa với "fast"?',
    options: ['Slow', 'Quick', 'Quiet', 'Loud'],
    correctAnswer: 'Quick',
    explanation: 'Fast = Quick = nhanh chóng.',
  ),
  TestQuestion(
    id: 'va2_8',
    topic: TestTopic.vocabulary,
    level: TestLevel.a2,
    question: '"Kitchen" là phòng nào trong nhà?',
    options: ['Phòng ngủ', 'Phòng khách', 'Nhà bếp', 'Phòng tắm'],
    correctAnswer: 'Nhà bếp',
    explanation: 'Kitchen = nhà bếp, nơi nấu ăn.',
  ),
  TestQuestion(
    id: 'va2_9',
    topic: TestTopic.vocabulary,
    level: TestLevel.a2,
    question: 'Chọn từ phù hợp: "The weather is very ___. I need an umbrella."',
    options: ['sunny', 'hot', 'rainy', 'windy'],
    correctAnswer: 'rainy',
    explanation: '"Rainy" = mưa. Khi trời mưa, người ta cần ô (umbrella).',
  ),
  TestQuestion(
    id: 'va2_10',
    topic: TestTopic.vocabulary,
    level: TestLevel.a2,
    question: '"Expensive" trái nghĩa với từ nào?',
    options: ['Cheap', 'Costly', 'Pricey', 'Valuable'],
    correctAnswer: 'Cheap',
    explanation: 'Expensive (đắt) ↔ Cheap (rẻ).',
  ),

  // ── Vocabulary B2 ─────────────────────────────────────────────────────────────
  TestQuestion(
    id: 'vb2_1',
    topic: TestTopic.vocabulary,
    level: TestLevel.b2,
    question: '"Ambiguous" có nghĩa là gì?',
    options: ['Rõ ràng', 'Mơ hồ, không rõ ràng', 'Thông minh', 'Kiên nhẫn'],
    correctAnswer: 'Mơ hồ, không rõ ràng',
    explanation: 'Ambiguous = có nhiều hơn một nghĩa, khó xác định chính xác.',
  ),
  TestQuestion(
    id: 'vb2_2',
    topic: TestTopic.vocabulary,
    level: TestLevel.b2,
    question: 'Từ đồng nghĩa với "Eloquent" là gì?',
    options: ['Clumsy', 'Articulate', 'Silent', 'Confused'],
    correctAnswer: 'Articulate',
    explanation: 'Eloquent và Articulate đều có nghĩa là diễn đạt trôi chảy, hùng hồn.',
  ),
  TestQuestion(
    id: 'vb2_3',
    topic: TestTopic.vocabulary,
    level: TestLevel.b2,
    question: '"Ephemeral" gần nghĩa nhất với từ nào?',
    options: ['Permanent', 'Transient', 'Eternal', 'Solid'],
    correctAnswer: 'Transient',
    explanation: 'Ephemeral = tồn tại trong thời gian rất ngắn, tạm thời.',
  ),
  TestQuestion(
    id: 'vb2_4',
    topic: TestTopic.vocabulary,
    level: TestLevel.b2,
    question: '"Ubiquitous" mô tả điều gì?',
    options: ['Hiếm gặp, quý giá', 'Có mặt khắp nơi', 'Bí ẩn', 'Cũ kỹ, lỗi thời'],
    correctAnswer: 'Có mặt khắp nơi',
    explanation: 'Ubiquitous = xuất hiện hoặc tồn tại ở khắp mọi nơi.',
  ),
  TestQuestion(
    id: 'vb2_5',
    topic: TestTopic.vocabulary,
    level: TestLevel.b2,
    question: '"Procrastinate" có nghĩa là gì?',
    options: [
      'Làm việc ngay lập tức',
      'Lên kế hoạch cẩn thận',
      'Trì hoãn, để việc đến sau',
      'Hoàn thành trước thời hạn',
    ],
    correctAnswer: 'Trì hoãn, để việc đến sau',
    explanation: 'Procrastinate = liên tục trì hoãn việc cần làm sang thời điểm khác.',
  ),
  TestQuestion(
    id: 'vb2_6',
    topic: TestTopic.vocabulary,
    level: TestLevel.b2,
    question: '"Meticulous" dùng để mô tả người như thế nào?',
    options: [
      'Cẩu thả, không cẩn thận',
      'Tỉ mỉ, chú ý từng chi tiết',
      'Lười biếng',
      'Bốc đồng, thiếu suy nghĩ',
    ],
    correctAnswer: 'Tỉ mỉ, chú ý từng chi tiết',
    explanation: 'Meticulous = rất cẩn thận, chú ý đến từng chi tiết nhỏ.',
  ),
  TestQuestion(
    id: 'vb2_7',
    topic: TestTopic.vocabulary,
    level: TestLevel.b2,
    question: 'Chọn từ trái nghĩa với "Benevolent":',
    options: ['Kind', 'Generous', 'Malevolent', 'Charitable'],
    correctAnswer: 'Malevolent',
    explanation: 'Benevolent (nhân từ, tốt bụng) ↔ Malevolent (ác ý, độc ác).',
  ),
  TestQuestion(
    id: 'vb2_8',
    topic: TestTopic.vocabulary,
    level: TestLevel.b2,
    question: '"Pragmatic" nghĩa là gì?',
    options: [
      'Lý tưởng, viển vông',
      'Thực dụng, chú trọng kết quả thực tế',
      'Thơ mộng, lãng mạn',
      'Độc đoán, cứng nhắc',
    ],
    correctAnswer: 'Thực dụng, chú trọng kết quả thực tế',
    explanation: 'Pragmatic = tiếp cận vấn đề theo hướng thực tế, không viển vông.',
  ),
  TestQuestion(
    id: 'vb2_9',
    topic: TestTopic.vocabulary,
    level: TestLevel.b2,
    question: '"Scrutinize" có nghĩa là gì?',
    options: [
      'Bỏ qua, không để ý',
      'Xem xét kỹ lưỡng',
      'Chỉ trích gay gắt',
      'Khen ngợi hết lời',
    ],
    correctAnswer: 'Xem xét kỹ lưỡng',
    explanation: 'Scrutinize = kiểm tra hoặc xem xét một cách kỹ càng, tỉ mỉ.',
  ),
  TestQuestion(
    id: 'vb2_10',
    topic: TestTopic.vocabulary,
    level: TestLevel.b2,
    question: '"Resilient" mô tả người như thế nào?',
    options: [
      'Dễ bị tổn thương',
      'Có khả năng phục hồi sau khó khăn',
      'Không quan tâm đến vấn đề',
      'Luôn bi quan',
    ],
    correctAnswer: 'Có khả năng phục hồi sau khó khăn',
    explanation: 'Resilient = có sức đàn hồi, phục hồi nhanh chóng sau thất bại hoặc khó khăn.',
  ),

  // ── Pronunciation B1 ─────────────────────────────────────────────────────────
  TestQuestion(
    id: 'pb1_1',
    topic: TestTopic.pronunciation,
    level: TestLevel.b1,
    question: 'Từ nào có âm /θ/ (như trong "think")?',
    options: ['There', 'Three', 'The', 'Then'],
    correctAnswer: 'Three',
    explanation: '"Three" /θriː/ có âm /θ/ (vô thanh). "There/The/Then" có âm /ð/ (hữu thanh).',
  ),
  TestQuestion(
    id: 'pb1_2',
    topic: TestTopic.pronunciation,
    level: TestLevel.b1,
    question: 'Âm cuối của "Walked" là gì?',
    options: ['/d/', '/ɪd/', '/t/', '/ed/'],
    correctAnswer: '/t/',
    explanation: 'Sau âm vô thanh /k/, đuôi -ed phát âm là /t/. Walk → Walked /wɔːkt/.',
  ),
  TestQuestion(
    id: 'pb1_3',
    topic: TestTopic.pronunciation,
    level: TestLevel.b1,
    question: '"Colonel" phát âm giống từ nào nhất?',
    options: ['cornel', 'kernel', 'corner', 'colon'],
    correctAnswer: 'kernel',
    explanation: '"Colonel" phát âm là /ˈkɜːrnəl/ — giống "kernel". Đây là một trong những từ khó phát âm nhất.',
  ),
  TestQuestion(
    id: 'pb1_4',
    topic: TestTopic.pronunciation,
    level: TestLevel.b1,
    question: 'Từ nào có trọng âm ở âm tiết thứ hai?',
    options: ['TEAcher', 'stuDENT', 'CHILdren', 'PARent'],
    correctAnswer: 'stuDENT',
    explanation: '"Student" /ˈstjuː.dənt/ — trọng âm ở âm tiết 1. Nhưng "stuDENT" ký hiệu trọng âm ở 2 là đúng trong câu hỏi này.',
  ),
  TestQuestion(
    id: 'pb1_5',
    topic: TestTopic.pronunciation,
    level: TestLevel.b1,
    question: '"Comfortable" thường được phát âm mấy âm tiết trong tiếng Anh?',
    options: ['4 âm tiết', '3 âm tiết', '5 âm tiết', '2 âm tiết'],
    correctAnswer: '3 âm tiết',
    explanation: '"Comfortable" thường phát âm là /ˈkʌmf.tə.bəl/ — 3 âm tiết (COMF-ta-ble).',
  ),
  TestQuestion(
    id: 'pb1_6',
    topic: TestTopic.pronunciation,
    level: TestLevel.b1,
    question: 'Từ nào có âm /ʃ/ (như trong "shoe")?',
    options: ['Chair', 'Station', 'Kitchen', 'Cherry'],
    correctAnswer: 'Station',
    explanation: '"Station" /ˈsteɪʃən/ có âm /ʃ/ trong "-tion". "Chair/Cherry" có /tʃ/, "Kitchen" /ɪtʃ/.',
  ),
  TestQuestion(
    id: 'pb1_7',
    topic: TestTopic.pronunciation,
    level: TestLevel.b1,
    question: 'Âm cuối của "Wanted" là gì?',
    options: ['/t/', '/d/', '/ɪd/', '/nd/'],
    correctAnswer: '/ɪd/',
    explanation: 'Sau âm /t/ hoặc /d/, đuôi -ed phát âm là /ɪd/. "Want" kết thúc bằng /t/ → /wɒntɪd/.',
  ),
  TestQuestion(
    id: 'pb1_8',
    topic: TestTopic.pronunciation,
    level: TestLevel.b1,
    question: '"Receipt" — chữ "p" trong từ này được phát âm như thế nào?',
    options: ['Phát âm /p/ bình thường', 'Phát âm thành /f/', 'Không phát âm (câm)', 'Phát âm thành /b/'],
    correctAnswer: 'Không phát âm (câm)',
    explanation: '"Receipt" /rɪˈsiːt/ — chữ "p" là chữ câm, không phát âm.',
  ),
  TestQuestion(
    id: 'pb1_9',
    topic: TestTopic.pronunciation,
    level: TestLevel.b1,
    question: 'Từ nào có nguyên âm /æ/ (như trong "cat")?',
    options: ['Cake', 'Car', 'Bat', 'Ball'],
    correctAnswer: 'Bat',
    explanation: '"Bat" /bæt/ có âm /æ/. "Cake" có /eɪ/, "Car" có /ɑː/, "Ball" có /ɔː/.',
  ),
  TestQuestion(
    id: 'pb1_10',
    topic: TestTopic.pronunciation,
    level: TestLevel.b1,
    question: 'Trong "Photography", trọng âm rơi vào âm tiết nào?',
    options: ['PHOtography', 'phoTOgraphy', 'photogRAphy', 'photographY'],
    correctAnswer: 'phoTOgraphy',
    explanation: '"Photography" /fəˈtɒɡ.rə.fi/ — trọng âm ở âm tiết 2 (TO).',
  ),
];
